import api from './axios'

export const getMembers = (params) => api.get('/members', { params })
export const getMember = (id) => api.get(`/members/${id}`)
export const getMemberStats = () => api.get('/members/stats')
export const getMemberInvoices = (id) => api.get(`/members/${id}/invoices`)
export const getMemberInvoicesWithPayments = (id, params) => api.get(`/members/${id}/invoices-with-payments`, { params })
export const getMemberPayments = (id) => api.get(`/members/${id}/payments`)
export const getMemberCalls = (id, params) => api.get(`/members/${id}/calls`, { params })
export const createMemberCall = (id, data) => api.post(`/members/${id}/calls`, data)
export const updateMemberCall = (id, callId, data) => api.put(`/members/${id}/calls/${callId}`, data)
export const getMemberReferrals = (id, params) => api.get(`/members/${id}/referrals`, { params })
export const createMemberReferral = (id, data) => api.post(`/members/${id}/referrals`, data)
export const createMember = (data) => api.post('/members', data)
export const updateMember = (id, data) => api.put(`/members/${id}`, data)
export const deleteMember = (id) => api.delete(`/members/${id}`)
export const enrollMember = (id, data) => api.post(`/members/${id}/enroll`, data)
export const renewMembership = (id, data) => api.post(`/members/${id}/renew`, data)
export const searchMembers = (query) => api.get('/members/search', { params: { q: query } })
export const getMemberTimeSlots = (id) => api.get(`/members/${id}/time-slots`)
export const setMemberTimeSlots = (id, timeSlots) => api.put(`/members/${id}/time-slots`, { timeSlots })
export const calculateUpgradeProration = (memberId, newPlanId) => api.get(`/members/${memberId}/upgrade/proration/${newPlanId}`)
export const upgradeMembership = (memberId, data) => api.post(`/members/${memberId}/upgrade`, data)

